#!/bin/sh

# /etc/X11/xinit/xinitrc.d/10-nvidia-oc.sh
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script

#!/bin/sh
# A script for overclocking Nvidia graphics card under Linux

nvidia-settings \
    -a "[gpu:0]/GPUGraphicsClockOffset[3]=100" \
    -a "[gpu:0]/GPUMemoryTransferRateOffset[3]=300"
nvidia-settings \
    -a "[gpu:1]/GPUGraphicsClockOffset[3]=100" \
    -a "[gpu:1]/GPUMemoryTransferRateOffset[3]=600"

exec xterm
