- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: restart-certbot
  service:
    name: certbot
    state: restarted

- name: restart-mail
  service:
    name: mail
    state: restarted
