- hosts: localhost
  vars_files: vars/main.yaml
  tasks:
    - name: tor image
      docker_image:
        build:
          args:
            TOR_VER: "{{ tor_ver }}"
          path: .
        name: quay.io/george_angel/tor
        tag: "{{ tor_ver }}_{{ tor_rel }}"
        push: yes
        source: build

- hosts: relays
  remote_user: root
  roles:
    - common
    - tor
  vars_files:
    - vars/main.yaml
    - vars/secret.yaml

- hosts: bridges
  remote_user: root
  roles:
    - common
    - tor
  vars_files:
    - vars/main.yaml
    - vars/secret.yaml
