- hosts: localhost
  vars_files: vars/main.yaml
  tasks:
    - name: Tor image
      docker_image:
        build:
          path: .
          args:
            TOR_VER: "{{ tor_ver }}"
        name: quay.io/george_angel/tor
        tag: "{{ tor_ver }}"
        push: yes
        source: build

- hosts: relays
  remote_user: root
  roles:
     - common
     - tor
  vars_files:
    - vars/main.yaml
    - vars/secret.yaml

- hosts: bridges
  remote_user: root
  roles:
     - common
     - tor
  vars_files:
    - vars/main.yaml
    - vars/secret.yaml
