- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400 # One day
  register: apt

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - docker.io
      - make
      - mosh
      - tmux

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
