- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - tmux
    - mosh
    - gnupg2
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - docker-ce
