- name: install certbot
  package:
    name: certbot
    state: present

- name: mail.service
  template:
    src: templates/mail.service.j2
    dest: /etc/systemd/system/mail.service
    mode: 0644
  notify:
    - daemon-reload
    - restart-mail

- name: systemd mail
  systemd:
    name: mail
    enabled: yes
    state: started
    daemon_reload: yes
