#!/bin/bash
set -e

if [[ "$1" == "bitcoin-cli" || "$1" == "bitcoin-tx" || "$1" == "test_bitcoin" ]]; then
  chown -R bitcoin /bitcoin/data
  exec gosu bitcoin "$@"
elif [[ "$1" == "bitcoind" ]]; then
  chown -R bitcoin /bitcoin/data
  exec gosu bitcoin "$@" -conf=/etc/bitcoin.conf
fi

exec "$@"
