#!/bin/bash

set -e

cat << EOF | sudo tee /etc/systemd/system/bitcoind.service >/dev/null
# /etc/systemd/system/bitcoind.service
[Unit]
Description=Bitcoin node
After=docker.service
Requires=docker.service

[Service]
Restart=on-failure
ExecStartPre=sh -c 'mountpoint -q ${DISK_MOUNT} || sudo mount ${DISK} ${DISK_MOUNT}'
ExecStartPre=sh -c 'test -d ${DISK_MOUNT}${BITCOIN_DATA_DIR} || sudo mkdir -p ${DISK_MOUNT}${BITCOIN_DATA_DIR}'
ExecStart=/bin/sh -c '\
 docker run --name=%p --rm \
 -v ${DISK_MOUNT}${BITCOIN_DATA_DIR}:/bitcoin/data:rw \
 -p 8333:8333 \
 -p 9735:9735 \
 ${IMAGE}'
ExecStop=/bin/sh -c 'docker stop -t 3 %p'

[Install]
WantedBy=multi-user.target
EOF

## On creation: `sudo systemctl enable bitcoind.service && sudo systemctl start bitcoind`
## On update: `sudo systemctl daemon-reload && sudo systemctl restart bitcoind.service`
sudo systemctl enable bitcoind.service && sudo systemctl start bitcoind

cat < EOF | sudo tee /usr/local/bin/bitcoin-cli >/dev/null
#!/bin/bash
docker run --rm --network container:bitcoind -v ${DISK_MOUNT}${BITCOIN_DATA_DIR}:/bitcoin/data:rw ${IMAGE} bitcoin-cli "\$@"
EOF
sudo chmod +x /usr/local/bin/bitcoin-cli
